apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      values: |-
        extraEnvs: 
        - name: ELASTIC_USERNAME
          valueFrom: 
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: username
        - name: ELASTIC_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password
        secret: 
          enabled: false
        
      releaseName: elasticsearch
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging

  syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
      - CreateNamespace=true