# Default values for employees.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: employees-deployment
  replicaCount: 2
  image: 
    name: 644435390668.dkr.ecr.eu-west-3.amazonaws.com/employees
    tag: 1.0.4

service:
  name: employees-service
  portListen: 3000
  portForward: 3000

tls:
  enable: true
  prodCertificate: false
  hostname: danielemployees.cloud
  email: daniel577000@gmail.com
  awsRegion: eu-west-3
  awsHostedZoneID: Z09020131AOXZ3LFNC5KB
  awsRole: arn:aws:iam::644435390668:role/daniel-cert-manager-route53
   
ingress:
  name: employees-nginx-ingress
  className: nginx

kibana:
  importDashboards: false
  namespace: logging
  jobName: kibana-import
  serviceName: kibana-kibana
  userName: elastic
  port: 5601
  dataViewImported: |
    {"attributes":{"fieldAttrs":"{}","fieldFormatMap":"{}","fields":"[]","name":"employees-logs","runtimeFieldMap":"{}","sourceFilters":"[]","timeFieldName":"@timestamp","title":"logstash-employees","typeMeta":"{}"},"coreMigrationVersion":"8.5.1","id":"3c63b18b-e284-4655-81d1-0b37b3b1c4bd","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2023-02-16T08:49:44.307Z","version":"WzEzOSwxXQ=="}
    {"excludedObjects":[],"excludedObjectsCount":0,"exportedCount":1,"missingRefCount":0,"missingReferences":[]}
  dashBoardImported: |
    {
      "version": "8.5.1",
      "objects": [
        {
          "id": "60fe58e0-adde-11ed-85c1-6df5bc677460",
          "type": "dashboard",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-16T09:43:34.006Z",
          "version": "WzEwMjEsMV0=",
          "attributes": {
            "title": "employees-dashboard",
            "hits": 0,
            "description": "",
            "panelsJSON": "[{\"version\":\"8.5.1\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":17,\"h\":13,\"i\":\"b59dbc9e-af1f-40a9-8c85-5d0670a93312\"},\"panelIndex\":\"b59dbc9e-af1f-40a9-8c85-5d0670a93312\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsMetric\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"3c63b18b-e284-4655-81d1-0b37b3b1c4bd\",\"name\":\"indexpattern-datasource-layer-1028c53c-3d97-49ba-b7b2-5d69a10219cc\"}],\"state\":{\"visualization\":{\"layerId\":\"1028c53c-3d97-49ba-b7b2-5d69a10219cc\",\"layerType\":\"data\",\"metricAccessor\":\"8453da30-fa1f-49e6-8caf-7efe183a3c26\",\"breakdownByAccessor\":\"c4a60b3c-2192-4308-8fe1-1a17dfa6dcf7\",\"palette\":{\"type\":\"palette\",\"name\":\"status\",\"params\":{\"name\":\"status\",\"reverse\":false,\"rangeType\":\"percent\",\"rangeMin\":0,\"rangeMax\":100,\"progression\":\"fixed\",\"stops\":[{\"color\":\"#209280\",\"stop\":33.33},{\"color\":\"#d6bf57\",\"stop\":66.66},{\"color\":\"#cc5642\",\"stop\":100}],\"steps\":3,\"colorStops\":[],\"continuity\":\"all\",\"maxSteps\":5}}},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"indexpattern\":{\"layers\":{\"1028c53c-3d97-49ba-b7b2-5d69a10219cc\":{\"columns\":{\"c4a60b3c-2192-4308-8fe1-1a17dfa6dcf7\":{\"label\":\"Top 5 values of meta.req.method.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"meta.req.method.keyword\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"8453da30-fa1f-49e6-8caf-7efe183a3c26\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"}}},\"8453da30-fa1f-49e6-8caf-7efe183a3c26\":{\"label\":\"Count of records\",\"customLabel\":false,\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"___records___\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"c4a60b3c-2192-4308-8fe1-1a17dfa6dcf7\",\"8453da30-fa1f-49e6-8caf-7efe183a3c26\"],\"incompleteColumns\":{}}}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{}}},{\"version\":\"8.5.1\",\"type\":\"lens\",\"gridData\":{\"x\":17,\"y\":0,\"w\":11,\"h\":13,\"i\":\"a785e775-97b7-4b15-8792-7238c66dc84c\"},\"panelIndex\":\"a785e775-97b7-4b15-8792-7238c66dc84c\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"3c63b18b-e284-4655-81d1-0b37b3b1c4bd\",\"name\":\"indexpattern-datasource-layer-dc8f6559-6145-4dc8-be96-3d4eb73cc627\"}],\"state\":{\"visualization\":{\"shape\":\"pie\",\"layers\":[{\"layerId\":\"dc8f6559-6145-4dc8-be96-3d4eb73cc627\",\"primaryGroups\":[\"3e1041c1-8dc1-4c85-b986-4492c8dedfab\"],\"metric\":\"95d0b533-47c4-4557-989f-93ff7c1dc98d\",\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"hide\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"indexpattern\":{\"layers\":{\"dc8f6559-6145-4dc8-be96-3d4eb73cc627\":{\"columns\":{\"3e1041c1-8dc1-4c85-b986-4492c8dedfab\":{\"label\":\"Top value of meta.req.headers.user-agent.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"meta.req.headers.user-agent.keyword\",\"isBucketed\":true,\"params\":{\"size\":1,\"orderBy\":{\"type\":\"column\",\"columnId\":\"95d0b533-47c4-4557-989f-93ff7c1dc98d\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"}}},\"95d0b533-47c4-4557-989f-93ff7c1dc98d\":{\"label\":\"Count of meta.req.headers.user-agent.keyword\",\"customLabel\":false,\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"meta.req.headers.user-agent.keyword\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"3e1041c1-8dc1-4c85-b986-4492c8dedfab\",\"95d0b533-47c4-4557-989f-93ff7c1dc98d\"],\"incompleteColumns\":{}}}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{},\"hidePanelTitles\":false},\"title\":\"Most used user agent to access app\"},{\"version\":\"8.5.1\",\"type\":\"lens\",\"gridData\":{\"x\":28,\"y\":0,\"w\":19,\"h\":13,\"i\":\"b39e353b-0a94-4e9e-bbf9-108eb43ed215\"},\"panelIndex\":\"b39e353b-0a94-4e9e-bbf9-108eb43ed215\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsDatatable\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"3c63b18b-e284-4655-81d1-0b37b3b1c4bd\",\"name\":\"indexpattern-datasource-layer-390777d3-2089-42d4-80da-1bf035723e32\"}],\"state\":{\"visualization\":{\"layerId\":\"390777d3-2089-42d4-80da-1bf035723e32\",\"layerType\":\"data\",\"columns\":[{\"columnId\":\"22239816-1335-475c-991f-c0e0f8f795a1\"},{\"columnId\":\"001b131e-5660-44ea-b256-5685443a21cc\"}]},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"indexpattern\":{\"layers\":{\"390777d3-2089-42d4-80da-1bf035723e32\":{\"columns\":{\"22239816-1335-475c-991f-c0e0f8f795a1\":{\"label\":\"URI\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"meta.req.url.keyword\",\"isBucketed\":true,\"params\":{\"size\":6,\"orderBy\":{\"type\":\"column\",\"columnId\":\"001b131e-5660-44ea-b256-5685443a21cc\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"secondaryFields\":[]},\"customLabel\":true},\"001b131e-5660-44ea-b256-5685443a21cc\":{\"label\":\"Number of entries\",\"customLabel\":true,\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"meta.req.url.keyword\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"22239816-1335-475c-991f-c0e0f8f795a1\",\"001b131e-5660-44ea-b256-5685443a21cc\"],\"incompleteColumns\":{}}}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{},\"hidePanelTitles\":false},\"title\":\"Num of entries to URI\"},{\"version\":\"8.5.1\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":13,\"w\":24,\"h\":15,\"i\":\"9e54da9b-68dd-4d14-8ac4-d06b3b7349fd\"},\"panelIndex\":\"9e54da9b-68dd-4d14-8ac4-d06b3b7349fd\",\"embeddableConfig\":{\"attributes\":{\"title\":\"\",\"visualizationType\":\"lnsXY\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"3c63b18b-e284-4655-81d1-0b37b3b1c4bd\",\"name\":\"indexpattern-datasource-layer-af5ad64d-e5df-4a14-b862-ffac1ea5ee03\"}],\"state\":{\"visualization\":{\"legend\":{\"isVisible\":true,\"position\":\"right\"},\"valueLabels\":\"hide\",\"fittingFunction\":\"None\",\"axisTitlesVisibilitySettings\":{\"x\":true,\"yLeft\":true,\"yRight\":true},\"tickLabelsVisibilitySettings\":{\"x\":true,\"yLeft\":true,\"yRight\":true},\"labelsOrientation\":{\"x\":0,\"yLeft\":0,\"yRight\":0},\"gridlinesVisibilitySettings\":{\"x\":true,\"yLeft\":true,\"yRight\":true},\"preferredSeriesType\":\"line\",\"layers\":[{\"layerId\":\"af5ad64d-e5df-4a14-b862-ffac1ea5ee03\",\"seriesType\":\"line\",\"xAccessor\":\"72e52698-754e-4066-a8ee-0af853e46ad5\",\"accessors\":[\"d5885ce2-18bc-4bdb-bbcb-1b56a60b0d8b\"],\"yConfig\":[{\"forAccessor\":\"d5885ce2-18bc-4bdb-bbcb-1b56a60b0d8b\",\"color\":\"#6092c0\"}],\"layerType\":\"data\"}]},\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"indexpattern\":{\"layers\":{\"af5ad64d-e5df-4a14-b862-ffac1ea5ee03\":{\"columns\":{\"72e52698-754e-4066-a8ee-0af853e46ad5\":{\"label\":\"meta.res.statusCode\",\"dataType\":\"number\",\"operationType\":\"range\",\"sourceField\":\"meta.res.statusCode\",\"isBucketed\":true,\"scale\":\"interval\",\"params\":{\"includeEmptyRows\":true,\"type\":\"histogram\",\"ranges\":[{\"from\":0,\"to\":1000,\"label\":\"\"}],\"maxBars\":\"auto\"}},\"d5885ce2-18bc-4bdb-bbcb-1b56a60b0d8b\":{\"label\":\"Count\",\"customLabel\":true,\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"meta.res.statusCode\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"72e52698-754e-4066-a8ee-0af853e46ad5\",\"d5885ce2-18bc-4bdb-bbcb-1b56a60b0d8b\"],\"incompleteColumns\":{}}}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{}}}]",
            "optionsJSON": "{\"useMargins\":true,\"syncColors\":false,\"syncTooltips\":false,\"hidePanelTitles\":false}",
            "version": 1,
            "timeRestore": false,
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
            }
          },
          "references": [
            {
              "type": "index-pattern",
              "id": "3c63b18b-e284-4655-81d1-0b37b3b1c4bd",
              "name": "b59dbc9e-af1f-40a9-8c85-5d0670a93312:indexpattern-datasource-layer-1028c53c-3d97-49ba-b7b2-5d69a10219cc"
            },
            {
              "type": "index-pattern",
              "id": "3c63b18b-e284-4655-81d1-0b37b3b1c4bd",
              "name": "a785e775-97b7-4b15-8792-7238c66dc84c:indexpattern-datasource-layer-dc8f6559-6145-4dc8-be96-3d4eb73cc627"
            },
            {
              "type": "index-pattern",
              "id": "3c63b18b-e284-4655-81d1-0b37b3b1c4bd",
              "name": "b39e353b-0a94-4e9e-bbf9-108eb43ed215:indexpattern-datasource-layer-390777d3-2089-42d4-80da-1bf035723e32"
            },
            {
              "type": "index-pattern",
              "id": "3c63b18b-e284-4655-81d1-0b37b3b1c4bd",
              "name": "9e54da9b-68dd-4d14-8ac4-d06b3b7349fd:indexpattern-datasource-layer-af5ad64d-e5df-4a14-b862-ffac1ea5ee03"
            }
          ],
          "migrationVersion": {
            "dashboard": "8.5.0"
          },
          "coreMigrationVersion": "8.5.1"
        },
        {
          "id": "3c63b18b-e284-4655-81d1-0b37b3b1c4bd",
          "type": "index-pattern",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-16T08:49:44.307Z",
          "version": "WzEzOSwxXQ==",
          "attributes": {
            "fieldAttrs": "{}",
            "title": "logstash-employees",
            "timeFieldName": "@timestamp",
            "sourceFilters": "[]",
            "fields": "[]",
            "fieldFormatMap": "{}",
            "typeMeta": "{}",
            "runtimeFieldMap": "{}",
            "name": "employees-logs"
          },
          "references": [],
          "migrationVersion": {
            "index-pattern": "8.0.0"
          },
          "coreMigrationVersion": "8.5.1"
        }
      ]
    }

# mongodb subchart
mongodb:
  architecture: replicaset
  arbiter:
    enabled: false
  auth:
    usernames: ["employees"]
    databases: ["employees"]
    existingSecret: "mongo-cred"
  replicaCount: 3