apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: security
spec:
  project: default
  source:
    helm:
      parameters:
      - name: "installCRDs"
        value: true
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: cert-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: security

  syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
      - CreateNamespace=true