apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Daniel-Yakov/employees-gitops-config.git
    targetRevision: HEAD
    path: infra-apps/efk-stack
  destination:
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true