apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.1.0
    helm:
      releaseName: kube-prometheus-stack
      values: |-
        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
        grafana:
          dashboardProviders:
            dashboardproviders.yaml:
            - name: dp1
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/dp1
          dashboardsConfigMaps: {
            dp1: "nginx-dashboard"
          }
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring

  syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true