apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.1.0
    helm:
      releaseName: kube-prometheus-stack
      values: |-
        defaultRules:
          create: false
        additionalPrometheusRulesMap: 
          custom-rules:
            groups:
            - name: portfolio
              rules:
              - alert: InstanceHighMemoryUsage
                expr: (100 - (avg by (instance) (node_memory_MemAvailable_bytes{job="node-exporter"}) / avg by (instance) (node_memory_MemTotal_bytes{job="node-exporter"})) * 100) > 10
                for: 1m
                labels:
                  severity: warning
                  alertname: InstanceHighMemoryUsage
                annotations:
                  summary: "Instance {{ $labels.instance }}: memory usage high"
                  description: "{{ $labels.instance }} use more than 10%"
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['...']
              group_wait: 20s
              group_interval: 4m
              repeat_interval: 4h
              receiver: 'null'
              routes:
              - receiver: 'slack-k8s'
                continue: true
            receivers:
            - name: 'null'
            - name: 'slack-k8s'
              slack_configs:
              - api_url: 'https://hooks.slack.com/services/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'
                channel: '#grafana-alerts'
                title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .Labels.alertname }}'
                text: >-
                  {{ range .Alerts }}
                    *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                  {{ end }}
                send_resolved: true
        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
        grafana:
          defaultDashboardsEnabled: false
          defaultDashboardsTimezone: Israel
          sidecar:
            provider:
            allowUiUpdates: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring

  syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true