{{- if .Values.tls.enable }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    {{- if .Values.tls.prodCertificate }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.tls.email }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-cluster-issuer-key
    solvers:
    - dns01:
        route53:
          region: {{ .Values.tls.awsRegion }}
          hostedZoneID: {{ .Values.tls.awsHostedZoneID }}
          role: {{ .Values.tls.awsRole }}
      selector:
        dnsZones:
          - {{ .Values.tls.hostname }}
{{- end }}