{{- if .Values.ingress.inableTLS }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: daniel577000@gmail.com
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-cluster-issuer-key
    solvers:
    - dns01:
        route53:
          region: eu-west-3
          hostedZoneID: Z09020131AOXZ3LFNC5KB
          role: arn:aws:iam::644435390668:role/daniel-cert-manager-route53
      selector:
        dnsZones:
          - {{ .Values.ingress.hostname }}
{{- end }}