apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
  {{- include "deployment.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
    {{- include "deployment.labels" . | indent 6 }}
  template:
    metadata:
      labels:
      {{- include "deployment.labels" . | indent 8 }}
    spec:
      containers:
      - name: employees-app
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-conf
              key: MONGO_URI
        resources:
          requests:
            memory: "30Mi"
            cpu: "32m"
          limits:
            memory: "64Mi"
            cpu: "64m"
            
