{{- if .Values.kibana.importDashboards }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.kibana.jobName }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Values.kibana.namespace }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: kibana-data
        configMap:
            name: kibana-data
            defaultMode: 0777
      containers:
      - name: kibana-import
        image: centos:centos7
        imagePullPolicy: IfNotPresent
        env:
        - name: KIBANA_URL
          value: {{ .Values.kibana.serviceName | quote }}
        - name: KIBANA_PORT
          value: {{ .Values.kibana.port | quote }}
        # found in elastic-sealed in infra-apps/
        - name: USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password
        command: ["/bin/sh","/kibana/curl-script.sh"]
        volumeMounts:
        - name: kibana-data
          mountPath: /kibana/
{{- end }}