apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |-
    server {
      listen 80;
      root /usr/share/nginx/html/;
      index index.html;

      location / {
        add_header From  "nginx";
        try_files $uri $uri/ index.html =404;
      }
    }