apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginxDeployment.name }}
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine-slim
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d
        - name: static
          mountPath: /usr/share/nginx/html
      volumes:
      - name: conf
        configMap:
          name: nginx-conf
      - name: static
        configMap:
          name: nginx-static