apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginxDeployment.portListen }}
      targetPort: {{ .Values.nginxDeployment.portForward }}