apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
  {{- include "deployment.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.portListen }}
      targetPort: {{ .Values.service.portForward }}
